config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/MondaicSupport/collaborations/dt-geo:
      branch: main
      repo: https://gitlab.com/MondaicSupport/collaborations/dt-geo
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-purple-molly.sh
        container: qc.acc_pokey-pumpkin-yak
  QC.Doc:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-sepia-lemur.sh
        container: qc.doc_blurry-alizarin-chamois
      gitlab.com/MondaicSupport/collaborations/dt-geo git:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-linen-flamingo.sh
        container: qc.doc_geeky-red-boar
      gitlab.com/MondaicSupport/collaborations/dt-geo markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-turquoise-beaver.sh
        container: qc.doc_freaky-charcoal-bison
  QC.Lic:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-thistle-warthog.sh
        container: qc.lic_breezy-ecru-mongoose
  QC.Sec:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-taupe-dhole.sh
        container: qc.sec_stealthy-cobalt-starfish
  QC.Sty:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-amethyst-beetle.sh
        container: qc.sty_bumpy-sangria-okapi
      gitlab.com/MondaicSupport/collaborations/dt-geo hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-gold-whale.sh
        container: qc.sty_beady-heliotrope-dachsbracke
      gitlab.com/MondaicSupport/collaborations/dt-geo jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-auburn-bombay.sh
        container: qc.sty_nippy-emerald-ragdoll
  QC.Uni:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-aqua-oyster.sh
        container: qc.uni_greasy-khaki-dragon
  QC.Ver:
    repos:
      gitlab.com/MondaicSupport/collaborations/dt-geo get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-green-mongoose.sh
        container: qc.ver_ugly-periwinkle-meerkat
timeout: 5400
